### ISSUE TITLE
Version without boostrap requirement

### ISSUE THREAD

**Issue by etcook** [justin-lau/ui-iconpicker#5]
This module is fantastic - great work. Unfortunately, I'm using Foundation on a current project. I read in another issue that you were potentially removing ui-bootstrap as a dependency. +1 to that

...and thank you again!

**Comment by justin-lau** [comment]
Sorry @etcook, by "ui-bootstrap" I actually meant the [UI Bootstrap Angular Directives by the AngularUI team](http://angular-ui.github.io/bootstrap/).

On the other hand, dropping Bootstrap itself is highly unlikely to happen. Without a backbone CSS framework the style of the icon picker will not be consistent with the rest of the adopting site. Choosing Bootstrap instead of Foundation is just a matter of personal choice. If there are requests to do so, I will consider to create a clone of the iconpicker that uses Foundation in the future.
